# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import countries_pb2 as countries__pb2


class CountriesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCountries = channel.unary_unary(
                '/Countries/GetCountries',
                request_serializer=countries__pb2.CountriesRequest.SerializeToString,
                response_deserializer=countries__pb2.CountriesResponse.FromString,
                )


class CountriesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCountries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountriesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCountries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCountries,
                    request_deserializer=countries__pb2.CountriesRequest.FromString,
                    response_serializer=countries__pb2.CountriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Countries', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Countries(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCountries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Countries/GetCountries',
            countries__pb2.CountriesRequest.SerializeToString,
            countries__pb2.CountriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
