# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countries.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countries.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63ountries.proto\"\'\n\x10\x43ountriesRequest\x12\x13\n\x0brequestBody\x18\x01 \x01(\t\"!\n\x11\x43ountriesResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2D\n\tCountries\x12\x37\n\x0cGetCountries\x12\x11.CountriesRequest\x1a\x12.CountriesResponse\"\x00\x62\x06proto3'
)




_COUNTRIESREQUEST = _descriptor.Descriptor(
  name='CountriesRequest',
  full_name='CountriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestBody', full_name='CountriesRequest.requestBody', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=58,
)


_COUNTRIESRESPONSE = _descriptor.Descriptor(
  name='CountriesResponse',
  full_name='CountriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='CountriesResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['CountriesRequest'] = _COUNTRIESREQUEST
DESCRIPTOR.message_types_by_name['CountriesResponse'] = _COUNTRIESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountriesRequest = _reflection.GeneratedProtocolMessageType('CountriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRIESREQUEST,
  '__module__' : 'countries_pb2'
  # @@protoc_insertion_point(class_scope:CountriesRequest)
  })
_sym_db.RegisterMessage(CountriesRequest)

CountriesResponse = _reflection.GeneratedProtocolMessageType('CountriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRIESRESPONSE,
  '__module__' : 'countries_pb2'
  # @@protoc_insertion_point(class_scope:CountriesResponse)
  })
_sym_db.RegisterMessage(CountriesResponse)



_COUNTRIES = _descriptor.ServiceDescriptor(
  name='Countries',
  full_name='Countries',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCountries',
    full_name='Countries.GetCountries',
    index=0,
    containing_service=None,
    input_type=_COUNTRIESREQUEST,
    output_type=_COUNTRIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRIES)

DESCRIPTOR.services_by_name['Countries'] = _COUNTRIES

# @@protoc_insertion_point(module_scope)
